version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    container_name: mysql-techchallenge
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .env

  app:
    build: .
    container_name: techchallenge-app
    ports:
      - "8080:8080"
      - "5005:5005" # <- porta de debug
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MERCADO_PAGO_ACCESS_TOKEN: ${MERCADO_PAGO_ACCESS_TOKEN}
      MERCADO_PAGO_COLLECTOR_ID: ${MERCADO_PAGO_COLLECTOR_ID}
      MERCADO_PAGO_POS_ID: ${MERCADO_PAGO_POS_ID}
    env_file:
      - .env

volumes:
  mysql_data:
